### ISSUE TITLE
how to get size in bytes?

### ISSUE THREAD

**Issue by KonradHoeffner** [sujayakar/rsdict#5]
Is there a way to calculate the total amount in bytes including heap that an instance of RsDict occupies in memory?

**Comment by sujayakar** [comment]
hi @KonradHoeffner, not yet. would you be looking for something like implementing the trait from [heapsize](https://github.com/servo/heapsize)?

**Comment by KonradHoeffner** [comment]
Just a simple method like `fn size_in_bytes(&self) -> usize {...}` would be enough for me.

**Comment by sujayakar** [comment]
I've merged #6 and published it to crates.io as version 0.0.6. let me know if that works for you!

**Comment by KonradHoeffner** [comment]
That works perfectly, thank you!
